import { Story } from "./types";

export const BACKUP_DIGG_STORIES: Story[] = [
  {
    id: "digg-1",
    title: "Global Climate Summit Establishes Crucial Carbon Compliance Accord",
    summary: "Representatives from over sixty nations have finalized a historic legal framework creating a global carbon enforcement threshold. The treaty penalizes non-compliant commercial maritime transport while subsidizing industrial clean grid expansions.",
    url: "https://www.cbsnews.com/news/global-climate-summit-carbon-compliance-accord/",
    publishedAt: "2026-06-02T22:15:00Z",
    youtubeVideoId: "gX3fAnY_1dI",
    youtubeVideoTitle: "CBS Evening News: Landmark Climate Treaty Finalized in Geneva",
    youtubeChannel: "CBS Evening News",
    viewsCount: 890000,
    trendingScore: 99,
    category: "Climate & Environment"
  },
  {
    id: "digg-2",
    title: "Federal Reserve Adjusts Policy Yields to Counteract Regional Housing Pressure",
    summary: "The Board of Governors enacted a quarter-point rate adjustment aimed at moderating high-density commercial real estate development while maintaining current federal mortgage benchmarks to support primary residential home buyers.",
    url: "https://www.cbsnews.com/news/federal-reserve-adjusts-interest-rates-housing-market/",
    publishedAt: "2026-06-02T20:50:00Z",
    youtubeVideoId: "DQacCB9tDaw",
    youtubeVideoTitle: "CBS Mornings: How the Federal Reserve Decision Impacts Your Mortgage",
    youtubeChannel: "CBS Mornings",
    viewsCount: 1250000,
    trendingScore: 98,
    category: "Finance"
  },
  {
    id: "digg-3",
    title: "Deep Space Telescope Detects Signatures of Water Oceans on Exoplanet Proxima b",
    summary: "Astronomers employing high-definition spectrograph equipment have identified distinct atmospheric elements indicating the presence of active saltwater oceans. The discovery marks the closest habitable liquid-water state candidate yet mapped.",
    url: "https://www.cbsnews.com/news/exoplanet-proxima-b-water-ocean-discovery/",
    publishedAt: "2026-06-02T19:30:00Z",
    youtubeVideoId: "29ECwWrnzdQ",
    youtubeVideoTitle: "60 Minutes: The Search for Habitable Worlds Beyond Our Solar System",
    youtubeChannel: "60 Minutes",
    viewsCount: 2150000,
    trendingScore: 96,
    category: "Space & Science"
  },
  {
    id: "digg-4",
    title: "Bilateral Trade Accord Concludes Multi-Year Agricultural Grid Dispute",
    summary: "Bilateral trade ministers signed a formal settlement resolution removing retaliatory food tariffs between North American and European maritime corridors, establishing streamlined mutual export certifications for organic product streams.",
    url: "https://www.cbsnews.com/news/bilateral-trade-agreement-agricultural-tariffs/",
    publishedAt: "2026-06-02T17:45:00Z",
    youtubeVideoId: "vB-SAnAatgA",
    youtubeVideoTitle: "CBS Reports: Global Shipping Routes and Tariff Reductions explained",
    youtubeChannel: "CBS News Reports",
    viewsCount: 460000,
    trendingScore: 94,
    category: "World News"
  },
  {
    id: "digg-5",
    title: "Supreme Court Clarifies Digital Marketplace Antitrust Guidelines",
    summary: "In a definitive 7-2 majority ruling, the high court established that tech companies cannot enforce exclusive platform routing defaults that restrict third-party payment system options. The ruling aims to increase market competition.",
    url: "https://www.cbsnews.com/news/supreme-court-marketplace-antitrust-ruling/",
    publishedAt: "2026-06-02T15:20:00Z",
    youtubeVideoId: "V_mepYmclHA",
    youtubeVideoTitle: "CBS Evening News: Breakdown of today's Landmark Supreme Court Ruling",
    youtubeChannel: "CBS Evening News",
    viewsCount: 1680000,
    trendingScore: 92,
    category: "Politics"
  },
  {
    id: "digg-6",
    title: "Renewable Fusion Ignition Loop Achieves Direct Continuous Energy Benchmark",
    summary: "National ignition laboratory coordinators announced they have sustained an active plasma core reaction yielding a net-positive output coefficient for over nine minutes, a major milestone on the path to grid-scale utility integration.",
    url: "https://www.cbsnews.com/news/plasma-ignition-milestone-fusion-power/",
    publishedAt: "2026-06-02T13:10:00Z",
    youtubeVideoId: "GZ7nU8oTPl8",
    youtubeVideoTitle: "CBS News: Fusion Reaction Reaches Record High Temperatures in Lab",
    youtubeChannel: "CBS News",
    viewsCount: 380000,
    trendingScore: 89,
    category: "Space & Science"
  },
  {
    id: "digg-7",
    title: "Major Infrastructure Act Allocates Strategic Funding to Deepwater Sea Ports",
    summary: "Federal transit authorities have initiated a multi-billion dollar capital improvement phase to expand dock drafts and acquire heavy-duty zero-emission automated cranes for seven primary East and West coast logistical hubs.",
    url: "https://www.cbsnews.com/news/deepwater-sea-port-infrastructure-funding/",
    publishedAt: "2026-06-02T11:40:00Z",
    youtubeVideoId: "fW_C97t6Eos",
    youtubeVideoTitle: "CBS Evening News: Infrastructure Improvements Target Supply Chain Delays",
    youtubeChannel: "CBS Evening News",
    viewsCount: 620000,
    trendingScore: 88,
    category: "Finance"
  },
  {
    id: "digg-8",
    title: "Biogenics Trial Achieves Groundbreaking Synaptic Pathway Mapping",
    summary: "Clinical researchers have finalized a comprehensive molecular map detail of human neural synapses, enabling targeted synthetic protein delivery mechanisms that could prevent neurological degeneration before onset.",
    url: "https://www.cbsnews.com/news/biogenic-trial-synaptic-mapping-neurological/",
    publishedAt: "2026-06-02T09:15:00Z",
    youtubeVideoId: "9g297XN6_Qo",
    youtubeVideoTitle: "60 Minutes: Behind the Medical Breakthrough mapping Brain Pathways",
    youtubeChannel: "60 Minutes",
    viewsCount: 740000,
    trendingScore: 87,
    category: "Space & Science"
  },
  {
    id: "digg-9",
    title: "International Coalition Announces Cooperative Cybersecurity Standards",
    summary: "Cyber intelligence agencies from forty nations have agreed to a standardized threat information sharing baseline and mutual protection structures to insulate sovereign electrical, water, and emergency logistics grids.",
    url: "https://www.cbsnews.com/news/international-cybersecurity-cooperation-agreement/",
    publishedAt: "2026-06-02T08:00:00Z",
    youtubeVideoId: "v73tSTZp9Xk",
    youtubeVideoTitle: "CBS Reports: Global Cybersecurity Treaties and Grid Vulnerabilities",
    youtubeChannel: "CBS News Reports",
    viewsCount: 970000,
    trendingScore: 85,
    category: "Politics"
  },
  {
    id: "digg-10",
    title: "Municipal Water Reclamation Initiative Receives Historic Regional Grant",
    summary: "A regional reclamation project designed to construct three high-performance reverse-osmosis recycling facilities has secured capital grants to process up to fifty-million gallons of drinkable water per day for local agricultural zones.",
    url: "https://www.cbsnews.com/news/municipal-water-reclamation-regional-grant/",
    publishedAt: "2026-06-02T06:30:00Z",
    youtubeVideoId: "U3O15n6TByk",
    youtubeVideoTitle: "CBS News Special: Sustaining Water Stocks in the American West",
    youtubeChannel: "CBS News Special Reports",
    viewsCount: 520000,
    trendingScore: 82,
    category: "Climate & Environment"
  }
];

export const BACKUP_CBS_STORIES: Story[] = [
  {
    id: "cbs-1",
    title: "Ducati Collezione 100 Motorcycle Collection",
    summary: "Ten limited-edition Ducati motorcycles dressed in liveries pulled from the brand's racing history, showcasing exceptional two-wheel performance and exclusivity.",
    url: "https://uncrate.com/ducati-collezione-100-motorcycle-collection/",
    publishedAt: "2026-06-02T22:00:00Z",
    youtubeVideoId: "2Xv8zN6pIeE",
    youtubeVideoTitle: "New Ducati Collezione 100 - First Ride Review",
    youtubeChannel: "Ducati Official",
    viewsCount: 650000,
    trendingScore: 99,
    category: "Cars",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-2",
    title: "LEGO Yamaha MT-10 SP",
    summary: "A 1,478-piece building set that allows motorcycle and engineering enthusiasts to put together their own highly detailed Yamaha MT-10 SP streetfighter model.",
    url: "https://uncrate.com/lego-yamaha-mt-10-sp/",
    publishedAt: "2026-06-02T20:00:00Z",
    youtubeVideoId: "9qHkndXmS0E",
    youtubeVideoTitle: "Lego Technic Yamaha MT-10 SP Review!",
    youtubeChannel: "RacingBrick",
    viewsCount: 820000,
    trendingScore: 97,
    category: "Gear",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1585366119957-e5733f3998cd?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-3",
    title: "Oura Ring 5 Smart Ring",
    summary: "The world's smallest smart ring tracker, refined with passive blood pressure monitoring, sleep telemetry, and dynamic breathing coaching metrics.",
    url: "https://uncrate.com/oura-ring-5-smart-ring/",
    publishedAt: "2026-06-02T19:00:00Z",
    youtubeVideoId: "zV2N8H98n2s",
    youtubeVideoTitle: "Oura Ring Gen 4/5 - Worth It After 6 Months?",
    youtubeChannel: "The Quantified Scientist",
    viewsCount: 450000,
    trendingScore: 95,
    category: "Tech",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1613521134141-f2d453aaad7d?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-4",
    title: "Louis Vuitton x UNICEF Unity Time Object Clock",
    summary: "A one-of-one diamond-set soccer-ball-shaped clock developed exclusively for Louis Vuitton's UNICEF auction house campaign, featuring exceptional high-horology.",
    url: "https://uncrate.com/louis-vuitton-x-unicef-unity-time-object-clock/",
    publishedAt: "2026-06-02T18:00:00Z",
    youtubeVideoId: "uL0Xf973f5Q",
    youtubeVideoTitle: "The Louis Vuitton x UNICEF Charity Auction Highlights",
    youtubeChannel: "Louis Vuitton",
    viewsCount: 310000,
    trendingScore: 92,
    category: "Gear",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-5",
    title: "Louis Vuitton: Virgil Abloh Ultimate Edition",
    summary: "Explore Virgil Abloh's brief, but hugely influential, tenure as artistic director of Louis Vuitton's menswear line through this luxury-grade hardbound coffee table volume.",
    url: "https://uncrate.com/louis-vuitton-virgil-abloh-ultimate-edition/",
    publishedAt: "2026-06-02T17:00:00Z",
    youtubeVideoId: "MfkA2K8Z_QY",
    youtubeVideoTitle: "Virgil Abloh's Best Louis Vuitton Designs Retrospective",
    youtubeChannel: "Highsnobiety",
    viewsCount: 180000,
    trendingScore: 91,
    category: "Style",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-6",
    title: "Arturia Memory V Software Synthesizer",
    summary: "A component-accurate software emulation of the legendary 1982 Memorymoog, widely considered Moog's final ultimate polyphonic analog hardware synthesizer.",
    url: "https://uncrate.com/arturia-memory-v-software-synthesizer/",
    publishedAt: "2026-06-02T16:00:00Z",
    youtubeVideoId: "bY36k6Y6aF0",
    youtubeVideoTitle: "Arturia Memory-V Demo and Sounds walkthrough",
    youtubeChannel: "Sonicstate",
    viewsCount: 410000,
    trendingScore: 89,
    category: "Tech",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-7",
    title: "Revolution: The History of Turntable Design",
    summary: "An expansive, beautiful publication charting the incredible historical, cultural, and mechanical engineering impacts of high-end analog record players and turntables.",
    url: "https://uncrate.com/revolution-the-history-of-turntable-design/",
    publishedAt: "2026-06-02T15:00:00Z",
    youtubeVideoId: "A3E20n-tWzo",
    youtubeVideoTitle: "The Art of Audiophile Turntable Design",
    youtubeChannel: "Vinyl Eyezz",
    viewsCount: 290000,
    trendingScore: 87,
    category: "Gear",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-8",
    title: "Tannoy Centenary Westminster Royal & Canterbury GR Loudspeakers",
    summary: "Two highly exclusive limited Prestige Gold Reference dual-concentric speakers, with restricted production runs honoring Tannoy's historic 100-year sound archive.",
    url: "https://uncrate.com/tannoy-centenary-westminster-royal-canterbury-gr-loudspeakers/",
    publishedAt: "2026-06-02T14:45:00Z",
    youtubeVideoId: "vA_kZ_T4w7w",
    youtubeVideoTitle: "Tannoy Westminster Royal Gold Reference Speakers Review",
    youtubeChannel: "Stereophile",
    viewsCount: 110000,
    trendingScore: 85,
    category: "Tech",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-9",
    title: "1M Mark Hotel World Cup Extravaganza Package",
    summary: "An ultra-premium four-night World Cup penthouse package in New York, complete with helicopter airport pick-up services and premium final tournament seats.",
    url: "https://uncrate.com/1m-mark-hotel-world-cup-extravaganza-package/",
    publishedAt: "2026-06-02T12:00:00Z",
    youtubeVideoId: "6d6D7nI0Q8M",
    youtubeVideoTitle: "Inside The $75,000/Night Mark Hotel Penthouse",
    youtubeChannel: "Architectural Digest",
    viewsCount: 780000,
    trendingScore: 83,
    category: "Vices",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-10",
    title: "Apple Sports App World Cup Features",
    summary: "Apple updates its free Sports application with comprehensive, real-time World Cup scores, layout lineups, and custom tournament metrics.",
    url: "https://uncrate.com/apple-sports-app-world-cup-features/",
    publishedAt: "2026-06-02T10:00:00Z",
    youtubeVideoId: "V5L2n4J8w_E",
    youtubeVideoTitle: "Apple Sports App Walkthrough & Features Review",
    youtubeChannel: "MacRumors",
    viewsCount: 120000,
    trendingScore: 80,
    category: "Tech",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop"
  }
];
