import { Story } from "./types";

export const BACKUP_DIGG_STORIES: Story[] = [
  {
    id: "digg-1",
    title: "Gemini 2.5 Ultra Sets New Milestones in Real-Time Agentic Planning",
    summary: "Google releases its Gemini 2.5 Ultra model, demonstrating sub-50ms speech-to-speech response times and advanced multi-step computer automation. The model acts as a native desktop companion capable of complex development workflows.",
    url: "https://digg.com/ai/google-gemini-2-5-ultra-agentic-planning-milestone",
    publishedAt: "2026-05-31T22:15:00Z",
    youtubeVideoId: "gX3fAnY_1dI",
    youtubeVideoTitle: "Google Gemini 2.5 Ultra: Hands-on Voice & Agent Demos",
    youtubeChannel: "TechDev Explained",
    viewsCount: 890000,
    trendingScore: 99,
    category: "AI Models"
  },
  {
    id: "digg-2",
    title: "GPT-5 'Strawberry' Architecture Opens to Public Developers",
    summary: "OpenAI officially launches its next-generation GPT-5 model, incorporating tree-of-thought reasoning paths that eliminate halluncinative logic errors. Developers report near-perfect automation on autonomous coding grids.",
    url: "https://digg.com/ai/openai-gpt-5-strawberry-developer-api-release",
    publishedAt: "2026-05-31T20:50:00Z",
    youtubeVideoId: "DQacCB9tDaw",
    youtubeVideoTitle: "GPT-5 First Impressions: The Power of Search & Reason",
    youtubeChannel: "OpenAI",
    viewsCount: 1250000,
    trendingScore: 98,
    category: "AI Models"
  },
  {
    id: "digg-3",
    title: "Boston Dynamics Electric Atlas Begins Commercial Logistics Trial",
    summary: "Boston Dynamics reveals its fully electric humanoid Atlas has successfully completed a three-month pilot at a major North American parcel sorting terminal. The robot operates autonomously at a 100% human-matching pace.",
    url: "https://digg.com/ai/boston-dynamics-electric-atlas-commercial-logistics-pilot",
    publishedAt: "2026-05-31T19:30:00Z",
    youtubeVideoId: "29ECwWrnzdQ",
    youtubeVideoTitle: "Electric Atlas Humanoid Completing Autonomous Warehouse Tasks",
    youtubeChannel: "Boston Dynamics",
    viewsCount: 2150000,
    trendingScore: 96,
    category: "Robotics"
  },
  {
    id: "digg-4",
    title: "Claude 4 dynamic Computer Use Sandbox Launches Secure API",
    summary: "Anthropic's latest Claude 4 agent system features seamless visual environment processing, allowing users to delegate multihour design tasks, testing pipelines, and browser automation loops with secure sandbox isolation.",
    url: "https://digg.com/ai/anthropic-claude-4-computer-use-sandbox-security",
    publishedAt: "2026-05-31T17:45:00Z",
    youtubeVideoId: "vB-SAnAatgA",
    youtubeVideoTitle: "Inside Anthropic's Next-Gen Claude 4 Computer Automation",
    youtubeChannel: "TechCrunch",
    viewsCount: 460000,
    trendingScore: 94,
    category: "AI agents"
  },
  {
    id: "digg-5",
    title: "Tesla Optimus Gen-3 Deployed Across Texas Gigafactories",
    summary: "Elon Musk reveals that 400 pre-production Optimus Gen-3 humanoids are active on manufacturing lines. The robots organize heavy battery cells and execute high-density circuit fittings autonomously.",
    url: "https://digg.com/ai/tesla-optimus-gen-3-humanoids-deployed-in-gigafactory",
    publishedAt: "2026-05-31T15:20:00Z",
    youtubeVideoId: "V_mepYmclHA",
    youtubeVideoTitle: "Optimus Gen-3 Working Autonomously inside Tesla Factory",
    youtubeChannel: "Tesla Update Team",
    viewsCount: 1680000,
    trendingScore: 92,
    category: "Robotics"
  },
  {
    id: "digg-6",
    title: "Apple Intelligence 2.0 Fully Integrates On-Device Private Cloud Compute",
    summary: "Apple publishes a hardware security protocol demonstrating zero-retention parameters for private cloud compute servers, satisfying federal security standards and enabling offline-grade biometric processing.",
    url: "https://digg.com/ai/apple-intelligence-2-private-cloud-compute-validation",
    publishedAt: "2026-05-31T13:10:00Z",
    youtubeVideoId: "GZ7nU8oTPl8",
    youtubeVideoTitle: "Apple Private Cloud Compute Security Architecture Deep Dive",
    youtubeChannel: "Apple Insider",
    viewsCount: 380000,
    trendingScore: 89,
    category: "AI Privacy"
  },
  {
    id: "digg-7",
    title: "Waymo Service Reaches 25 Cities, Marks 15 Million Safe Driverless Miles",
    summary: "Waymo extends its autonomous operations to major metropolitan grids including Miami and Chicago. Telemetry records zero severe incidents, cementing autonomous transit as a safe solution.",
    url: "https://digg.com/ai/waymo-autonomous-ride-hailing-expansion-city-approval",
    publishedAt: "2026-05-31T11:40:00Z",
    youtubeVideoId: "fW_C97t6Eos",
    youtubeVideoTitle: "Waymo Driverless Taxi Testing: 15 Million Milestone",
    youtubeChannel: "CoreTech Insights",
    viewsCount: 620000,
    trendingScore: 88,
    category: "Autonomous Systems"
  },
  {
    id: "digg-8",
    title: "Neuralink Recipient Demonstrates Mind-Controlled High-Speed Terminal Coding",
    summary: "Neuralink's latest clinical candidate demonstrates high-fidelity interface manipulation, achieving a record-breaking 120 letters-per-minute target using direct neurological cursor activation.",
    url: "https://digg.com/ai/neuralink-clinical-recipient-demonstrates-eyes-free-terminal-coding",
    publishedAt: "2026-05-31T09:15:00Z",
    youtubeVideoId: "9g297XN6_Qo",
    youtubeVideoTitle: "Neuralink Mind-Control Interface Speeds in Clinical Trials",
    youtubeChannel: "BioTech Watch",
    viewsCount: 740000,
    trendingScore: 87,
    category: "Neural Tech"
  },
  {
    id: "digg-9",
    title: "Meta Llama 4 Open Source Ecosystem Beats Closed Models on Code Benchmarks",
    summary: "Meta's highly anticipated Llama 4 model family launches with fully open-weight files. The flagship model outperforms closed solutions on standard SWE-bench tests, sparking localized AI deployment projects globally.",
    url: "https://digg.com/ai/meta-llama-4-open-source-release-swe-bench",
    publishedAt: "2026-05-31T08:00:00Z",
    youtubeVideoId: "v73tSTZp9Xk",
    youtubeVideoTitle: "Llama 4: The Ultimate Open-Source Model Launch",
    youtubeChannel: "Fireship",
    viewsCount: 970000,
    trendingScore: 85,
    category: "Open Source"
  },
  {
    id: "digg-10",
    title: "Fifty Nations Convene at Geneva for Historic AI Safety Treaty Accord",
    summary: "International representatives sign a foundational code of conducts banning sub-millisecond automated financial trading bots and establishing a security licensing rubric for clusters exceeding 10^26 FLOPs.",
    url: "https://digg.com/ai/geneva-global-safety-treaty-autonomous-computing",
    publishedAt: "2026-05-31T06:30:00Z",
    youtubeVideoId: "U3O15n6TByk",
    youtubeVideoTitle: "The AI Safety Treaty Accord: What Was Decided",
    youtubeChannel: "Legal Eagle",
    viewsCount: 520000,
    trendingScore: 82,
    category: "AI Policy"
  }
];

export const BACKUP_CBS_STORIES: Story[] = [
  {
    id: "cbs-1",
    title: "Ducati Collezione 100 Motorcycle Collection",
    summary: "Ten limited-edition Ducati motorcycles dressed in liveries pulled from the brand's racing history, showcasing exceptional two-wheel performance and exclusivity.",
    url: "https://uncrate.com/ducati-collezione-100-motorcycle-collection/",
    publishedAt: "2026-06-02T22:00:00Z",
    youtubeVideoId: "2Xv8zN6pIeE",
    youtubeVideoTitle: "New Ducati Collezione 100 - First Ride Review",
    youtubeChannel: "Ducati Official",
    viewsCount: 650000,
    trendingScore: 99,
    category: "Cars",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-2",
    title: "LEGO Yamaha MT-10 SP",
    summary: "A 1,478-piece building set that allows motorcycle and engineering enthusiasts to put together their own highly detailed Yamaha MT-10 SP streetfighter model.",
    url: "https://uncrate.com/lego-yamaha-mt-10-sp/",
    publishedAt: "2026-06-02T20:00:00Z",
    youtubeVideoId: "9qHkndXmS0E",
    youtubeVideoTitle: "Lego Technic Yamaha MT-10 SP Review!",
    youtubeChannel: "RacingBrick",
    viewsCount: 820000,
    trendingScore: 97,
    category: "Gear",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1585366119957-e5733f3998cd?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-3",
    title: "Oura Ring 5 Smart Ring",
    summary: "The world's smallest smart ring tracker, refined with passive blood pressure monitoring, sleep telemetry, and dynamic breathing coaching metrics.",
    url: "https://uncrate.com/oura-ring-5-smart-ring/",
    publishedAt: "2026-06-02T19:00:00Z",
    youtubeVideoId: "zV2N8H98n2s",
    youtubeVideoTitle: "Oura Ring Gen 4/5 - Worth It After 6 Months?",
    youtubeChannel: "The Quantified Scientist",
    viewsCount: 450000,
    trendingScore: 95,
    category: "Tech",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1613521134141-f2d453aaad7d?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-4",
    title: "Louis Vuitton x UNICEF Unity Time Object Clock",
    summary: "A one-of-one diamond-set soccer-ball-shaped clock developed exclusively for Louis Vuitton's UNICEF auction house campaign, featuring exceptional high-horology.",
    url: "https://uncrate.com/louis-vuitton-x-unicef-unity-time-object-clock/",
    publishedAt: "2026-06-02T18:00:00Z",
    youtubeVideoId: "uL0Xf973f5Q",
    youtubeVideoTitle: "The Louis Vuitton x UNICEF Charity Auction Highlights",
    youtubeChannel: "Louis Vuitton",
    viewsCount: 310000,
    trendingScore: 92,
    category: "Gear",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-5",
    title: "Louis Vuitton: Virgil Abloh Ultimate Edition",
    summary: "Explore Virgil Abloh's brief, but hugely influential, tenure as artistic director of Louis Vuitton's menswear line through this luxury-grade hardbound coffee table volume.",
    url: "https://uncrate.com/louis-vuitton-virgil-abloh-ultimate-edition/",
    publishedAt: "2026-06-02T17:00:00Z",
    youtubeVideoId: "MfkA2K8Z_QY",
    youtubeVideoTitle: "Virgil Abloh's Best Louis Vuitton Designs Retrospective",
    youtubeChannel: "Highsnobiety",
    viewsCount: 180000,
    trendingScore: 91,
    category: "Style",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-6",
    title: "Arturia Memory V Software Synthesizer",
    summary: "A component-accurate software emulation of the legendary 1982 Memorymoog, widely considered Moog's final ultimate polyphonic analog hardware synthesizer.",
    url: "https://uncrate.com/arturia-memory-v-software-synthesizer/",
    publishedAt: "2026-06-02T16:00:00Z",
    youtubeVideoId: "bY36k6Y6aF0",
    youtubeVideoTitle: "Arturia Memory-V Demo and Sounds walkthrough",
    youtubeChannel: "Sonicstate",
    viewsCount: 410000,
    trendingScore: 89,
    category: "Tech",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-7",
    title: "Revolution: The History of Turntable Design",
    summary: "An expansive, beautiful publication charting the incredible historical, cultural, and mechanical engineering impacts of high-end analog record players and turntables.",
    url: "https://uncrate.com/revolution-the-history-of-turntable-design/",
    publishedAt: "2026-06-02T15:00:00Z",
    youtubeVideoId: "A3E20n-tWzo",
    youtubeVideoTitle: "The Art of Audiophile Turntable Design",
    youtubeChannel: "Vinyl Eyezz",
    viewsCount: 290000,
    trendingScore: 87,
    category: "Gear",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-8",
    title: "Tannoy Centenary Westminster Royal & Canterbury GR Loudspeakers",
    summary: "Two highly exclusive limited Prestige Gold Reference dual-concentric speakers, with restricted production runs honoring Tannoy's historic 100-year sound archive.",
    url: "https://uncrate.com/tannoy-centenary-westminster-royal-canterbury-gr-loudspeakers/",
    publishedAt: "2026-06-02T14:45:00Z",
    youtubeVideoId: "vA_kZ_T4w7w",
    youtubeVideoTitle: "Tannoy Westminster Royal Gold Reference Speakers Review",
    youtubeChannel: "Stereophile",
    viewsCount: 110000,
    trendingScore: 85,
    category: "Tech",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-9",
    title: "1M Mark Hotel World Cup Extravaganza Package",
    summary: "An ultra-premium four-night World Cup penthouse package in New York, complete with helicopter airport pick-up services and premium final tournament seats.",
    url: "https://uncrate.com/1m-mark-hotel-world-cup-extravaganza-package/",
    publishedAt: "2026-06-02T12:00:00Z",
    youtubeVideoId: "6d6D7nI0Q8M",
    youtubeVideoTitle: "Inside The $75,000/Night Mark Hotel Penthouse",
    youtubeChannel: "Architectural Digest",
    viewsCount: 780000,
    trendingScore: 83,
    category: "Vices",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop"
  },
  {
    id: "cbs-10",
    title: "Apple Sports App World Cup Features",
    summary: "Apple updates its free Sports application with comprehensive, real-time World Cup scores, layout lineups, and custom tournament metrics.",
    url: "https://uncrate.com/apple-sports-app-world-cup-features/",
    publishedAt: "2026-06-02T10:00:00Z",
    youtubeVideoId: "V5L2n4J8w_E",
    youtubeVideoTitle: "Apple Sports App Walkthrough & Features Review",
    youtubeChannel: "MacRumors",
    viewsCount: 120000,
    trendingScore: 80,
    category: "Tech",
    itemThumbnailUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop"
  }
];
