import { Story } from "./types";

export const BACKUP_DIGG_STORIES: Story[] = [
  {
    id: "digg-1",
    title: "Gemini 2.5 Ultra Sets New Milestones in Real-Time Agentic Planning",
    summary: "Google releases its Gemini 2.5 Ultra model, demonstrating sub-50ms speech-to-speech response times and advanced multi-step computer automation. The model acts as a native desktop companion capable of complex development workflows.",
    url: "https://digg.com/ai/google-gemini-2-5-ultra-agentic-planning-milestone",
    publishedAt: "2026-05-31T22:15:00Z",
    youtubeVideoId: "gX3fAnY_1dI",
    youtubeVideoTitle: "Google Gemini 2.5 Ultra: Hands-on Voice & Agent Demos",
    youtubeChannel: "TechDev Explained",
    viewsCount: 890000,
    trendingScore: 99,
    category: "AI Models"
  },
  {
    id: "digg-2",
    title: "GPT-5 'Strawberry' Architecture Opens to Public Developers",
    summary: "OpenAI officially launches its next-generation GPT-5 model, incorporating tree-of-thought reasoning paths that eliminate halluncinative logic errors. Developers report near-perfect automation on autonomous coding grids.",
    url: "https://digg.com/ai/openai-gpt-5-strawberry-developer-api-release",
    publishedAt: "2026-05-31T20:50:00Z",
    youtubeVideoId: "DQacCB9tDaw",
    youtubeVideoTitle: "GPT-5 First Impressions: The Power of Search & Reason",
    youtubeChannel: "OpenAI",
    viewsCount: 1250000,
    trendingScore: 98,
    category: "AI Models"
  },
  {
    id: "digg-3",
    title: "Boston Dynamics Electric Atlas Begins Commercial Logistics Trial",
    summary: "Boston Dynamics reveals its fully electric humanoid Atlas has successfully completed a three-month pilot at a major North American parcel sorting terminal. The robot operates autonomously at a 100% human-matching pace.",
    url: "https://digg.com/ai/boston-dynamics-electric-atlas-commercial-logistics-pilot",
    publishedAt: "2026-05-31T19:30:00Z",
    youtubeVideoId: "29ECwWrnzdQ",
    youtubeVideoTitle: "Electric Atlas Humanoid Completing Autonomous Warehouse Tasks",
    youtubeChannel: "Boston Dynamics",
    viewsCount: 2150000,
    trendingScore: 96,
    category: "Robotics"
  },
  {
    id: "digg-4",
    title: "Claude 4 dynamic Computer Use Sandbox Launches Secure API",
    summary: "Anthropic's latest Claude 4 agent system features seamless visual environment processing, allowing users to delegate multihour design tasks, testing pipelines, and browser automation loops with secure sandbox isolation.",
    url: "https://digg.com/ai/anthropic-claude-4-computer-use-sandbox-security",
    publishedAt: "2026-05-31T17:45:00Z",
    youtubeVideoId: "vB-SAnAatgA",
    youtubeVideoTitle: "Inside Anthropic's Next-Gen Claude 4 Computer Automation",
    youtubeChannel: "TechCrunch",
    viewsCount: 460000,
    trendingScore: 94,
    category: "AI agents"
  },
  {
    id: "digg-5",
    title: "Tesla Optimus Gen-3 Deployed Across Texas Gigafactories",
    summary: "Elon Musk reveals that 400 pre-production Optimus Gen-3 humanoids are active on manufacturing lines. The robots organize heavy battery cells and execute high-density circuit fittings autonomously.",
    url: "https://digg.com/ai/tesla-optimus-gen-3-humanoids-deployed-in-gigafactory",
    publishedAt: "2026-05-31T15:20:00Z",
    youtubeVideoId: "V_mepYmclHA",
    youtubeVideoTitle: "Optimus Gen-3 Working Autonomously inside Tesla Factory",
    youtubeChannel: "Tesla Update Team",
    viewsCount: 1680000,
    trendingScore: 92,
    category: "Robotics"
  },
  {
    id: "digg-6",
    title: "Apple Intelligence 2.0 Fully Integrates On-Device Private Cloud Compute",
    summary: "Apple publishes a hardware security protocol demonstrating zero-retention parameters for private cloud compute servers, satisfying federal security standards and enabling offline-grade biometric processing.",
    url: "https://digg.com/ai/apple-intelligence-2-private-cloud-compute-validation",
    publishedAt: "2026-05-31T13:10:00Z",
    youtubeVideoId: "GZ7nU8oTPl8",
    youtubeVideoTitle: "Apple Private Cloud Compute Security Architecture Deep Dive",
    youtubeChannel: "Apple Insider",
    viewsCount: 380000,
    trendingScore: 89,
    category: "AI Privacy"
  },
  {
    id: "digg-7",
    title: "Waymo Service Reaches 25 Cities, Marks 15 Million Safe Driverless Miles",
    summary: "Waymo extends its autonomous operations to major metropolitan grids including Miami and Chicago. Telemetry records zero severe incidents, cementing autonomous transit as a safe solution.",
    url: "https://digg.com/ai/waymo-autonomous-ride-hailing-expansion-city-approval",
    publishedAt: "2026-05-31T11:40:00Z",
    youtubeVideoId: "fW_C97t6Eos",
    youtubeVideoTitle: "Waymo Driverless Taxi Testing: 15 Million Milestone",
    youtubeChannel: "CoreTech Insights",
    viewsCount: 620000,
    trendingScore: 88,
    category: "Autonomous Systems"
  },
  {
    id: "digg-8",
    title: "Neuralink Recipient Demonstrates Mind-Controlled High-Speed Terminal Coding",
    summary: "Neuralink's latest clinical candidate demonstrates high-fidelity interface manipulation, achieving a record-breaking 120 letters-per-minute target using direct neurological cursor activation.",
    url: "https://digg.com/ai/neuralink-clinical-recipient-demonstrates-eyes-free-terminal-coding",
    publishedAt: "2026-05-31T09:15:00Z",
    youtubeVideoId: "9g297XN6_Qo",
    youtubeVideoTitle: "Neuralink Mind-Control Interface Speeds in Clinical Trials",
    youtubeChannel: "BioTech Watch",
    viewsCount: 740000,
    trendingScore: 87,
    category: "Neural Tech"
  },
  {
    id: "digg-9",
    title: "Meta Llama 4 Open Source Ecosystem Beats Closed Models on Code Benchmarks",
    summary: "Meta's highly anticipated Llama 4 model family launches with fully open-weight files. The flagship model outperforms closed solutions on standard SWE-bench tests, sparking localized AI deployment projects globally.",
    url: "https://digg.com/ai/meta-llama-4-open-source-release-swe-bench",
    publishedAt: "2026-05-31T08:00:00Z",
    youtubeVideoId: "v73tSTZp9Xk",
    youtubeVideoTitle: "Llama 4: The Ultimate Open-Source Model Launch",
    youtubeChannel: "Fireship",
    viewsCount: 970000,
    trendingScore: 85,
    category: "Open Source"
  },
  {
    id: "digg-10",
    title: "Fifty Nations Convene at Geneva for Historic AI Safety Treaty Accord",
    summary: "International representatives sign a foundational code of conducts banning sub-millisecond automated financial trading bots and establishing a security licensing rubric for clusters exceeding 10^26 FLOPs.",
    url: "https://digg.com/ai/geneva-global-safety-treaty-autonomous-computing",
    publishedAt: "2026-05-31T06:30:00Z",
    youtubeVideoId: "U3O15n6TByk",
    youtubeVideoTitle: "The AI Safety Treaty Accord: What Was Decided",
    youtubeChannel: "Legal Eagle",
    viewsCount: 520000,
    trendingScore: 82,
    category: "AI Policy"
  }
];

export const BACKUP_CBS_STORIES: Story[] = [
  {
    id: "cbs-1",
    title: "SpaceX Starship Flight 8 Achieves Perfect Landing Ring Catches at Starbase",
    summary: "SpaceX records another engineering success as Starship Flight 8 completes a precise multi-trajectory orbital path, culminating in both the Super Heavy booster and Starship upper stage caught by the launch pad tower.",
    url: "https://www.cbsnews.com/news/spacex-starship-flight-8-tower-ring-catches-boic-chica/",
    publishedAt: "2026-05-31T22:45:00Z",
    youtubeVideoId: "GZ7nU8oTPl8",
    youtubeVideoTitle: "Flight 8 Booster Catch: Visual Telemetry Breakdown",
    youtubeChannel: "Everyday Astronaut",
    viewsCount: 3400000,
    trendingScore: 99,
    category: "Space Exploration"
  },
  {
    id: "cbs-2",
    title: "Federal Reserve Enacts Rate Cut, Citing Resilient Production Core",
    summary: "The Board of Governors approves a 25 basis point reduction in target treasury margins, signaling confidence in sustained stabilization of national consumer indices and strong household indices.",
    url: "https://www.cbsnews.com/news/federal-reserve-enacts-interest-rate-cut-briefing-june/",
    publishedAt: "2026-05-31T21:15:00Z",
    youtubeVideoId: "gG9gBfA1k8A",
    youtubeVideoTitle: "Federal Reserve Board Financial Forecast Briefing",
    youtubeChannel: "Bloomberg Markets",
    viewsCount: 220000,
    trendingScore: 94,
    category: "Finance"
  },
  {
    id: "cbs-3",
    title: "NASA Artemis Lunar Lander Engine Passes Deep Zero-G Chamber Trials",
    summary: "NASA's integrated human landing vessel engines conclude 15 consecutive thermal sequence fires inside high-vacuum chambers, clearing primary testing requirements for scheduled high-orbit Lunar voyages.",
    url: "https://www.cbsnews.com/news/nasa-artemis-lander-engines-certification/",
    publishedAt: "2026-05-31T19:50:00Z",
    youtubeVideoId: "H-83SgU3XJg",
    youtubeVideoTitle: "NASA Lunarsuit & Artemis Space Lander Update",
    youtubeChannel: "CBS News",
    viewsCount: 450000,
    trendingScore: 92,
    category: "Space Exploration"
  },
  {
    id: "cbs-4",
    title: "Bipartisan Conservation Act Allocates $800M for Wilderness Expansion",
    summary: "Bipartisan Congressional legislators designate substantial funding to protect and expand boundaries of national conservation grids. The bill restores historical bridges and paths across twelve key reserves.",
    url: "https://www.cbsnews.com/news/national-wilderness-preservation-funding-pathway-restoration/",
    publishedAt: "2026-05-31T17:30:00Z",
    youtubeVideoId: "w_Rj8aY8w34",
    youtubeVideoTitle: "Protecting America's National Parks: New Allotments",
    youtubeChannel: "CBS Sunday Morning",
    viewsCount: 310000,
    trendingScore: 89,
    category: "Conservation"
  },
  {
    id: "cbs-5",
    title: "Heat Dome Alerts Sound For Combined Metro Eastern Seaboard Region",
    summary: "The National Meteorological Agency broadcasts warnings with heat index calculations hitting 108 degrees Fahrenheit. Municipalities coordinate with community cooling centers to provide safety.",
    url: "https://www.cbsnews.com/news/coastal-heat-dome-warnings-cooling-center-access/",
    publishedAt: "2026-05-31T15:40:00Z",
    youtubeVideoId: "pW_XpTqZidM",
    youtubeVideoTitle: "Record Meteorological Heatwaves Grip Eastern USA",
    youtubeChannel: "CBS Evening News",
    viewsCount: 580000,
    trendingScore: 88,
    category: "National Weather"
  },
  {
    id: "cbs-6",
    title: "Federal Agency Approves $3.5B Midwest Smart Grid Power Upgrades",
    summary: "Energy administrators authorize a historic infrastructure initiative to replace legacy sub-stations with smart optical transformers across six Midwest states, aimed at stabilizing summer loads.",
    url: "https://www.cbsnews.com/news/federal-grant-midwest-electric-grid-modernization/",
    publishedAt: "2026-05-31T13:15:00Z",
    youtubeVideoId: "zXQZ7o07Kq4",
    youtubeVideoTitle: "Modernizing the US Electric Grid: Energy Transmission Plans",
    youtubeChannel: "CNBC",
    viewsCount: 410000,
    trendingScore: 86,
    category: "Infrastructure"
  },
  {
    id: "cbs-7",
    title: "Supreme Court Guidelines Stand on Water Microplastic Emission Controls",
    summary: "The high court issues a landmark 6-3 opinion validating federal agency regulatory scopes to enforce digital tracking registers for micro-plastics discharged by chemical processing plants.",
    url: "https://www.cbsnews.com/news/supreme-court-judicial-review-epa-microplastic-compliance/",
    publishedAt: "2026-05-31T11:20:00Z",
    youtubeVideoId: "_dFmR29I5Gk",
    youtubeVideoTitle: "Supreme Court Water Regulation Ruling: Detailed Review",
    youtubeChannel: "PBS NewsHour",
    viewsCount: 290000,
    trendingScore: 85,
    category: "National Policy"
  },
  {
    id: "cbs-8",
    title: "Surgical mRNA Treatment for Brain Tumors Enters Phase II Multi-Center Trials",
    summary: "National Institutes of Health scientists report positive results in clinical tumor sequence target maps. Personalized therapy induces localized antibody responses against rapid glioma cells.",
    url: "https://www.cbsnews.com/news/nih-personalized-mrna-oncology-trials-glioma-success/",
    publishedAt: "2026-05-31T09:00:00Z",
    youtubeVideoId: "QYkYmC6D5gA",
    youtubeVideoTitle: "Medical Breakthrough: Personal Oncology Vaccines",
    youtubeChannel: "Science News Today",
    viewsCount: 510000,
    trendingScore: 84,
    category: "Biotech & Medicine"
  },
  {
    id: "cbs-9",
    title: "Florida Marine Salvage Locates Pristine 18th Century Trade Vessel",
    summary: "Deep-water sonar coordinates off Key West confirm a wooden cargo vessel from 1740. Specialized crews retrieve intact navigation map cases, silver currency weights, and ceramic cargo.",
    url: "https://www.cbsnews.com/news/florida-key-west-archeological-salvage-spanish-vessel/",
    publishedAt: "2026-05-31T08:10:00Z",
    youtubeVideoId: "_m5vGfL3h7E",
    youtubeVideoTitle: "Colonial Shipwreck Located and Explored by Sonar Crews",
    youtubeChannel: "Smithsonian Channel",
    viewsCount: 780000,
    trendingScore: 81,
    category: "History & Science"
  },
  {
    id: "cbs-10",
    title: "National Weather Reports Heavy Rainfall Totals in Northwest Coast Region",
    summary: "Sub-tropical moisture ribbons dump up to six inches of rain in portions of coastal Oregon and Washington, sparking high-flow tributary warnings and localized road closure reviews.",
    url: "https://www.cbsnews.com/news/pacific-northwest-heavy-precipitation-tributary-risks/",
    publishedAt: "2026-05-31T06:15:00Z",
    youtubeVideoId: "pL5S5V9e0m8",
    youtubeVideoTitle: "Rainstorms Grip the Pacific Northwest Shorelines",
    youtubeChannel: "ABC News US",
    viewsCount: 320000,
    trendingScore: 78,
    category: "Climate & Safety"
  }
];
